# Generated by Django 5.0.4 on 2024-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_rename_finished_at_todo_done_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="done_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
