# Generated by Django 5.0.4 on 2024-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_todo_done_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="done_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
