# Generated by Django 5.0.4 on 2024-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0006_alter_todo_done_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="done_date",
            field=models.DateField(null=True),
        ),
    ]
